/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    projects: Project;
    companies: Company;
    experience: Experience;
    roles: Role;
    'skill-categories': SkillCategory;
    skills: Skill;
    'capability-areas': CapabilityArea;
    education: Education;
    recommendations: Recommendation;
    'contact-submissions': ContactSubmission;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    companies: CompaniesSelect<false> | CompaniesSelect<true>;
    experience: ExperienceSelect<false> | ExperienceSelect<true>;
    roles: RolesSelect<false> | RolesSelect<true>;
    'skill-categories': SkillCategoriesSelect<false> | SkillCategoriesSelect<true>;
    skills: SkillsSelect<false> | SkillsSelect<true>;
    'capability-areas': CapabilityAreasSelect<false> | CapabilityAreasSelect<true>;
    education: EducationSelect<false> | EducationSelect<true>;
    recommendations: RecommendationsSelect<false> | RecommendationsSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    hero: Hero;
    about: About;
  };
  globalsSelect: {
    hero: HeroSelect<false> | HeroSelect<true>;
    about: AboutSelect<false> | AboutSelect<true>;
  };
  locale: null;
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: string;
  title: string;
  /**
   * Auto-generated from title if left empty
   */
  slug: string;
  /**
   * Plain text for cards, meta tags, and OG images (max 200 chars)
   */
  shortDescription: string;
  projectType: 'professional' | 'startup' | 'open-source' | 'personal' | 'experiment';
  status: 'live' | 'in-progress' | 'archived';
  /**
   * Role this project was built under
   */
  experienceRole?: (string | null) | Role;
  role?: ('solo-developer' | 'lead-engineer' | 'core-contributor' | 'contributor' | 'architect' | 'tech-lead') | null;
  overview?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * What problem does this project solve?
   */
  problemStatement?: string | null;
  /**
   * Areas of the project you owned or led
   */
  ownershipAreas?:
    | {
        area: string;
        id?: string | null;
      }[]
    | null;
  /**
   * High-level architecture overview
   */
  architectureSummary?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Key technical decisions and their reasoning
   */
  technicalDecisions?:
    | {
        decision: string;
        reasoning?: string | null;
        tradeoffs?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Notable constraints or challenges
   */
  constraints?:
    | {
        constraint: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Quantifiable impact metrics
   */
  impactMetrics?:
    | {
        /**
         * Metric name (e.g. "Page Load Time")
         */
        label: string;
        /**
         * Metric value (e.g. "↓ 40%")
         */
        value: string;
        /**
         * Additional context for this metric
         */
        description?: string | null;
        /**
         * Show on the home page impact grid
         */
        featured?: boolean | null;
        /**
         * Display order (lower = first)
         */
        order?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Technologies used in this project
   */
  techStack?: (string | Skill)[] | null;
  links?: {
    /**
     * GitHub repository URL
     */
    github?: string | null;
    /**
     * Live/production URL
     */
    liveUrl?: string | null;
    /**
     * External case study URL
     */
    caseStudy?: string | null;
  };
  /**
   * Primary image for cards and hero sections
   */
  coverImage?: (string | null) | Media;
  media?:
    | {
        asset: string | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  startDate?: string | null;
  endDate?: string | null;
  /**
   * Show on the home page
   */
  featured?: boolean | null;
  /**
   * Visible on the public site
   */
  public?: boolean | null;
  /**
   * Display order (lower = first)
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roles".
 */
export interface Role {
  id: string;
  title: string;
  company: string | Company;
  startDate: string;
  /**
   * Leave empty for current role
   */
  endDate?: string | null;
  /**
   * Currently in this role
   */
  current?: boolean | null;
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Skills used in this role
   */
  skills?: (string | Skill)[] | null;
  ownershipLevel?: ('contributor' | 'lead' | 'architect' | 'manager') | null;
  /**
   * Quantifiable impact metrics
   */
  impactMetrics?:
    | {
        /**
         * Metric name (e.g. "Page Load Time")
         */
        label: string;
        /**
         * Metric value (e.g. "↓ 40%")
         */
        value: string;
        /**
         * Additional context for the metric
         */
        description?: string | null;
        /**
         * Show on the home page impact grid
         */
        featured?: boolean | null;
        /**
         * Display order (lower = first)
         */
        order?: number | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "companies".
 */
export interface Company {
  id: string;
  name: string;
  location?: string | null;
  /**
   * Company website URL
   */
  website?: string | null;
  logo?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * Describe the image for screen readers and SEO
   */
  alt?: string | null;
  /**
   * Category prefix for this upload
   */
  folder?: ('general' | 'companies' | 'projects' | 'about' | 'experience' | 'hero') | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skills".
 */
export interface Skill {
  id: string;
  name: string;
  category: string | SkillCategory;
  /**
   * Display order (lower = first)
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skill-categories".
 */
export interface SkillCategory {
  id: string;
  /**
   * Display name (e.g. "Frontend Framework")
   */
  label: string;
  /**
   * Slug identifier (e.g. "frontend-framework")
   */
  value: string;
  /**
   * Display order (lower = first)
   */
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experience".
 */
export interface Experience {
  id: string;
  company: string | Company;
  employmentType: 'full-time' | 'part-time' | 'contract' | 'freelance' | 'internship';
  locationType: 'on-site' | 'remote' | 'hybrid';
  /**
   * Roles held at this company
   */
  roles: (string | Role)[];
  /**
   * Auto-computed from earliest role start date
   */
  startDate?: string | null;
  /**
   * Auto-computed from latest role end date (empty if any role is current)
   */
  endDate?: string | null;
  media?:
    | {
        asset: string | Media;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "capability-areas".
 */
export interface CapabilityArea {
  id: string;
  /**
   * Display name (e.g. "Frontend & Mobile")
   */
  label: string;
  /**
   * Short description of this capability area
   */
  description: string;
  /**
   * Skill categories included in this area
   */
  categories: (string | SkillCategory)[];
  /**
   * Display order (lower = first)
   */
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "education".
 */
export interface Education {
  id: string;
  institution: string;
  /**
   * Institution website URL
   */
  website?: string | null;
  /**
   * e.g. Bachelor of Science
   */
  degree: string;
  /**
   * e.g. Mathematics and Computer Science
   */
  fieldOfStudy?: string | null;
  /**
   * e.g. Second Class Upper Division
   */
  honours?: string | null;
  startDate: string;
  /**
   * Leave empty if currently enrolled
   */
  endDate?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  location?: string | null;
  /**
   * Display order (lower = first)
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recommendations".
 */
export interface Recommendation {
  id: string;
  name: string;
  /**
   * Their job title, e.g. "Senior Engineer at Microsoft"
   */
  title: string;
  /**
   * How they know you, e.g. "Worked together on MSAL Android"
   */
  relationship?: string | null;
  /**
   * Contact email (not displayed publicly)
   */
  email?: string | null;
  /**
   * Contact phone (not displayed publicly)
   */
  phone?: string | null;
  message: string;
  status?: ('pending' | 'approved' | 'rejected') | null;
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: string;
  name: string;
  email: string;
  message: string;
  status?: ('unread' | 'read') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'projects';
        value: string | Project;
      } | null)
    | ({
        relationTo: 'companies';
        value: string | Company;
      } | null)
    | ({
        relationTo: 'experience';
        value: string | Experience;
      } | null)
    | ({
        relationTo: 'roles';
        value: string | Role;
      } | null)
    | ({
        relationTo: 'skill-categories';
        value: string | SkillCategory;
      } | null)
    | ({
        relationTo: 'skills';
        value: string | Skill;
      } | null)
    | ({
        relationTo: 'capability-areas';
        value: string | CapabilityArea;
      } | null)
    | ({
        relationTo: 'education';
        value: string | Education;
      } | null)
    | ({
        relationTo: 'recommendations';
        value: string | Recommendation;
      } | null)
    | ({
        relationTo: 'contact-submissions';
        value: string | ContactSubmission;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  shortDescription?: T;
  projectType?: T;
  status?: T;
  experienceRole?: T;
  role?: T;
  overview?: T;
  problemStatement?: T;
  ownershipAreas?:
    | T
    | {
        area?: T;
        id?: T;
      };
  architectureSummary?: T;
  technicalDecisions?:
    | T
    | {
        decision?: T;
        reasoning?: T;
        tradeoffs?: T;
        id?: T;
      };
  constraints?:
    | T
    | {
        constraint?: T;
        id?: T;
      };
  impactMetrics?:
    | T
    | {
        label?: T;
        value?: T;
        description?: T;
        featured?: T;
        order?: T;
        id?: T;
      };
  techStack?: T;
  links?:
    | T
    | {
        github?: T;
        liveUrl?: T;
        caseStudy?: T;
      };
  coverImage?: T;
  media?:
    | T
    | {
        asset?: T;
        caption?: T;
        id?: T;
      };
  startDate?: T;
  endDate?: T;
  featured?: T;
  public?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "companies_select".
 */
export interface CompaniesSelect<T extends boolean = true> {
  name?: T;
  location?: T;
  website?: T;
  logo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experience_select".
 */
export interface ExperienceSelect<T extends boolean = true> {
  company?: T;
  employmentType?: T;
  locationType?: T;
  roles?: T;
  startDate?: T;
  endDate?: T;
  media?:
    | T
    | {
        asset?: T;
        description?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roles_select".
 */
export interface RolesSelect<T extends boolean = true> {
  title?: T;
  company?: T;
  startDate?: T;
  endDate?: T;
  current?: T;
  description?: T;
  skills?: T;
  ownershipLevel?: T;
  impactMetrics?:
    | T
    | {
        label?: T;
        value?: T;
        description?: T;
        featured?: T;
        order?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skill-categories_select".
 */
export interface SkillCategoriesSelect<T extends boolean = true> {
  label?: T;
  value?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skills_select".
 */
export interface SkillsSelect<T extends boolean = true> {
  name?: T;
  category?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "capability-areas_select".
 */
export interface CapabilityAreasSelect<T extends boolean = true> {
  label?: T;
  description?: T;
  categories?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "education_select".
 */
export interface EducationSelect<T extends boolean = true> {
  institution?: T;
  website?: T;
  degree?: T;
  fieldOfStudy?: T;
  honours?: T;
  startDate?: T;
  endDate?: T;
  description?: T;
  location?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recommendations_select".
 */
export interface RecommendationsSelect<T extends boolean = true> {
  name?: T;
  title?: T;
  relationship?: T;
  email?: T;
  phone?: T;
  message?: T;
  status?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  message?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero".
 */
export interface Hero {
  id: string;
  /**
   * Page title used for SEO and the browser tab
   */
  title: string;
  /**
   * Status line shown above the name
   */
  statusText: string;
  primaryCta: {
    label: string;
    href: string;
  };
  secondaryCta: {
    label: string;
    href: string;
  };
  stats?:
    | {
        /**
         * e.g. "8 yrs", "400+", "4+"
         */
        value: string;
        /**
         * e.g. "engineering", "TS files migrated"
         */
        label: string;
        /**
         * Show in illustration
         */
        useInIllustration?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Uploadable résumé (PDF)
   */
  resume?: (string | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about".
 */
export interface About {
  id: string;
  /**
   * Full name
   */
  name: string;
  /**
   * Title shown above the name
   */
  title: string;
  /**
   * Tagline / title shown below the name
   */
  subtitle: string;
  /**
   * Short intro paragraph (used in hero section)
   */
  bio: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Current location (shown in about facts sidebar)
   */
  location: string;
  /**
   * Year started engineering — used to compute years of experience
   */
  startYear: number;
  /**
   * Profile photo
   */
  photo?: (string | null) | Media;
  /**
   * Section heading
   */
  heading: string;
  /**
   * 2–3 paragraphs about background & philosophy
   */
  overview: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Optional extra facts appended after auto-generated ones (Location, Experience, Focus, Education)
   */
  facts?:
    | {
        /**
         * e.g. "Location", "Experience", "Focus"
         */
        label: string;
        /**
         * e.g. "Nairobi, Kenya", "8+ years"
         */
        value: string;
        id?: string | null;
      }[]
    | null;
  quote?: {
    /**
     * An inspiring or personal quote
     */
    text?: string | null;
    /**
     * Who said it
     */
    attribution?: string | null;
  };
  contact: {
    /**
     * Contact section heading
     */
    heading?: string | null;
    /**
     * Short CTA message below the heading
     */
    description?: string | null;
    /**
     * Contact email address
     */
    email: string;
    socials?:
      | {
          platform: 'github' | 'linkedin' | 'twitter' | 'stackoverflow' | 'youtube' | 'medium' | 'other';
          /**
           * Full URL to social profile
           */
          url: string;
          /**
           * Optional display text (e.g. "GitHub")
           */
          label?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero_select".
 */
export interface HeroSelect<T extends boolean = true> {
  title?: T;
  statusText?: T;
  primaryCta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  secondaryCta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        useInIllustration?: T;
        id?: T;
      };
  resume?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about_select".
 */
export interface AboutSelect<T extends boolean = true> {
  name?: T;
  title?: T;
  subtitle?: T;
  bio?: T;
  location?: T;
  startYear?: T;
  photo?: T;
  heading?: T;
  overview?: T;
  facts?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  quote?:
    | T
    | {
        text?: T;
        attribution?: T;
      };
  contact?:
    | T
    | {
        heading?: T;
        description?: T;
        email?: T;
        socials?:
          | T
          | {
              platform?: T;
              url?: T;
              label?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}